on: [push]

jobs:
    deploy_job:
      runs-on: self-hosted
      name: exoleos-website CI
      steps:
        # To use this repository's private action, you must check out the repository
        - name: Checkout
        - uses: actions/checkout@v3

        - name: Install Dependencies
          run: npm ci
        - name: Build
          run: npm run build

        - name: deploy file to server
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
              username: 'creator'
              server: '${{ secrets.SERVER_IP }}'
              ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
              local_path: './build/*'
              remote_path: '/var/www/html/exoleos'
              sftpArgs: '-o ConnectTimeout=5'
